# Generated by Django 2.2.5 on 2022-01-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bulletinFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField()),
                ('txt_path', models.CharField(max_length=255)),
                ('img_path', models.CharField(max_length=255)),
            ],
        ),
    ]
