# Generated by Django 2.2.5 on 2022-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_auto_20220122_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinfeed',
            name='img_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bulletinfeed',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bulletinfeed',
            name='txt_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bulletinfeed',
            name='upload_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='profile_img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
