# Generated by Django 2.2.5 on 2022-01-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_auto_20220123_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletinfeed',
            old_name='txt_path',
            new_name='content',
        ),
    ]
